# https://golangci-lint.run/docs/configuration/file
version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod

linters:
  default: standard
  exclusions:
    presets:
      - common-false-positives
      - std-error-handling
